=== netresearch/dhl-module-shipping-core/etc/shipping_options.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="carriers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="carrier">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="carrierCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="packageLevelOptions" type="shippingOptionList" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="itemLevelOptions" type="shippingOptionList" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="metaData" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="imageUrl" type="xs:string" minOccurs="0"/>
                                        <xs:element name="commentsBefore" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="comment" type="commentConfig"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="commentsAfter" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="comment" type="commentConfig"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="footnotes" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="footnote">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="content" type="xs:string"/>
                                                                <xs:element name="footnoteId" type="xs:string"/>
                                                                <xs:element name="subjects" type="subjectsList" minOccurs="0"/>
                                                                <xs:element name="subjectsMustBeSelected" type="xs:boolean" minOccurs="0"/>
                                                                <xs:element name="subjectsMustBeAvailable" type="xs:boolean" minOccurs="0"/>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="compatibilityData" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="rule">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="incompatibilityRule" type="xs:boolean"/>
                                                    <xs:element name="subjects" type="subjectsList"/>
                                                    <xs:element name="errorMessage" type="xs:string"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="shippingOptionList">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="shippingOption">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="code" type="xs:string"/>
                        <xs:element name="label" type="xs:string"/>
                        <xs:element name="inputs">
                            <xs:complexType>
                                <xs:sequence maxOccurs="unbounded">
                                    <xs:element name="input">
                                        <xs:complexType>
                                            <xs:all>
                                                <xs:element name="code" type="xs:string"/>
                                                <xs:element name="label" type="xs:string"/>
                                                <xs:element name="labelVisible" type="xs:boolean" minOccurs="0"/>
                                                <xs:element name="inputType" type="xs:string"/>
                                                <xs:element name="options" minOccurs="0">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="option" maxOccurs="unbounded">
                                                                <xs:complexType>
                                                                    <xs:all>
                                                                        <xs:element name="label" type="xs:string"/>
                                                                        <xs:element name="value" type="xs:string" minOccurs="0"/>
                                                                        <xs:element name="disabled" type="xs:boolean" minOccurs="0"/>
                                                                    </xs:all>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="tooltip" type="xs:string" minOccurs="0"/>
                                                <xs:element name="placeholder" type="xs:string" minOccurs="0"/>
                                                <xs:element name="sortOrder" type="xs:integer" minOccurs="0"/>
                                                <xs:element name="validationRules" minOccurs="0">
                                                    <xs:complexType>
                                                        <xs:sequence maxOccurs="unbounded" minOccurs="1">
                                                            <xs:element name="rule">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                                        <xs:element name="param" minOccurs="0" maxOccurs="unbounded"/>
                                                                    </xs:sequence>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="comment" type="commentConfig" minOccurs="0"/>
                                                <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
                                            </xs:all>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="enabledForCheckout" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="enabledForAutocreate" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="enabledForPackaging" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="availableAtPostalFacility" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="packagingReadonly" type="xs:boolean" minOccurs="0"/>
                        <xs:element name="sortOrder" type="xs:integer" minOccurs="0"/>
                        <xs:element name="routes" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="route" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="origin" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                <xs:element name="destinations" minOccurs="1">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="destination" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="subjectsList">
        <xs:sequence>
            <xs:element name="subject" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="commentConfig">
        <xs:all>
            <xs:element name="content" type="xs:string"/>
            <xs:element name="footnoteId" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== netresearch/dhl-module-shipping-core/etc/adminhtml/shipping_options.xml
<?xml version="1.0" ?>
<carriers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Dhl_ShippingCore/etc/shipping_options.xsd">
    <carrier code="base">
        <packageOptions>
            <shippingOption code="packageWeight">
                <label>Package Details</label>
                <inputs>
                    <input code="weight">
                        <label>Total Weight</label>
                        <inputType>number</inputType>
                    </input>
                    <input code="weightUnit">
                        <label>Weight Unit</label>
                        <inputType>static</inputType>
                        <disabled>true</disabled>
                    </input>
                </inputs>
            </shippingOption>
            <shippingOption code="packageSize">
                <label>Package Size</label>
                <inputs>
                    <input code="width">
                        <label>Width</label>
                        <inputType>number</inputType>
                    </input>
                    <input code="height">
                        <label>Height</label>
                        <inputType>number</inputType>
                    </input>
                    <input code="length">
                        <label>Length</label>
                        <inputType>number</inputType>
                    </input>
                    <input code="sizeUnit">
                        <label>Size Unit</label>
                        <inputType>static</inputType>
                        <disabled>true</disabled>
                    </input>
                </inputs>
            </shippingOption>
            <shippingOption code="packageCustoms">
                <label>Customs Data</label>
                <inputs>
                    <input code="customsValue">
                        <label>Customs Value</label>
                        <inputType>price</inputType>
                    </input>
                    <input code="exportDescription">
                        <label>Package Description</label>
                        <inputType>textarea</inputType>
                    </input>
                    <input code="termsOfTrade" defaultConfigValue="dhlshippingsolutions/dhlglobalwebservices/shipment_defaults/terms_of_trade">
                        <label>Terms of Trade</label>
                        <inputType>select</inputType>
                    </input>
                    <input code="contentType" defaultConfigValue="dhlshippingsolutions/dhlglobalwebservices/shipment_defaults/export_content_type">
                        <label>Export Content Type</label>
                        <inputType>select</inputType>
                    </input>
                    <input code="explanation" defaultConfigValue="dhlshippingsolutions/dhlglobalwebservices/shipment_defaults/export_content_explanation">
                        <label>Export Content Explanation</label>
                        <inputType>text</inputType>
                    </input>
                </inputs>
            </shippingOption>
        </packageOptions>
        <itemOptions>
            <itemShippingOptions itemId="0">
                <shippingOptions>
                    <shippingOption code="details">
                        <label>Item Details</label>
                        <inputs>
                            <input code="productId">
                                <inputType>hidden</inputType>
                            </input>
                            <input code="productName">
                                <label>Product Name</label>
                                <inputType>static</inputType>
                                <disabled>true</disabled>
                            </input>
                            <input code="price">
                                <inputType>hidden</inputType>
                            </input>
                            <input code="weight">
                                <label>Weight</label>
                                <inputType>number</inputType>
                            </input>
                            <input code="qtyToShip">
                                <label>Quantity to Ship</label>
                                <inputType>static</inputType>
                                <disabled>true</disabled>
                            </input>
                            <input code="qty">
                                <label>Quantity</label>
                                <inputType>number</inputType>
                            </input>
                        </inputs>
                    </shippingOption>
                    <shippingOption code="itemCustoms">
                        <label>Customs Data</label>
                        <inputs>
                            <input code="hsCode">
                                <sortOrder>10</sortOrder>
                                <label>HS Code</label>
                                <inputType>text</inputType>
                            </input>
                            <input code="exportDescription">
                                <sortOrder>20</sortOrder>
                                <label>Export Description</label>
                                <inputType>textarea</inputType>
                            </input>
                            <input code="customsValue">
                                <sortOrder>30</sortOrder>
                                <label>Customs Value</label>
                                <inputType>price</inputType>
                            </input>
                            <input code="countryOfOrigin">
                                <sortOrder>40</sortOrder>
                                <label>Country of Origin</label>
                                <inputType>select</inputType>
                            </input>
                        </inputs>
                    </shippingOption>
                </shippingOptions>
            </itemShippingOptions>
        </itemOptions>
    </carrier>
</carriers>

=== netresearch/dhl-module-shipping-core/etc/shipping_options.xml
<?xml version="1.0" ?>
<options xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Dhl_ShippingCore/etc/shipping_options.xsd">
    <item>
      <shippingOption>
          <code>abv</code>
          <label></label>
          <inputs>
              <input>
                  <inputType></inputType>
                  <code></code>
                  <label></label>
                  <options>
                      <option>
                          <label>123</label>
                          <value></value>
                          <disabled>warum</disabled>
                      </option>
                  </options>
              </input>
          </inputs>
      </shippingOption>
        <shippingOption>
            <code>abc</code>
            <code>adas</code>
            <label></label>
            <inputs>
                <input>
                    <inputType></inputType>
                    <code></code>
                    <label></label>
                    <options>
                        <option>
                            <label>123</label>
                            <value></value>
                            <disabled>warum</disabled>
                        </option>
                    </options>
                </input>
            </inputs>
        </shippingOption>
    </item>
</options>
